### ISSUE TITLE
mysql bug

### ISSUE THREAD

**Issue by trueqap** [gregor20sw/MailcowDNS-Updater-Cloudflare-Hetzner#1]
Hello Gregor,

This is exactly the solution I've been looking for, I'm glad I don't have to start from scratch! :) I tried to run your code, but unfortunately, I'm getting this error:

```
./cf.sh: line 68: mysql: command not found
./cf.sh: line 72: mysql: command not found
```

I can't seem to find the error in the code. Do you have any ideas?

**Comment by gregor20sw** [comment]
Hello @trueqap,

Thank you for bringing this to my attention. I've addressed the issue you mentioned. The script no longer relies on having mysql installed on your system. Instead, it now utilizes the SQL within the Docker container, ensuring a smoother experience without external dependencies.

Please pull the latest version and give it another try. Let me know if you encounter any further issues or if everything is working as expected now.

Best regards,
Gregor
